# ---- builder stage ----
FROM golang:1.26 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /app/js-network-api ./cmd/js-network-api

# ---- final stage ----
FROM scratch

WORKDIR /app

COPY --from=builder /app/js-network-api .
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY ./urls.txt ./urls.txt

CMD ["./js-network-api"]
