# define what version of go image do we use
FROM golang:1.26.5

# make dir inside this root path
WORKDIR /app

# Copy and Paste the file you want into the image
COPY go.mod go.sum ./

# run the cli go mod download inside this image
RUN go mod download

# copy all relevant files into the image
COPY cmd/js-network-api/*.go ./cmd/js-network-api/
COPY pkg/urls-reader/*.go ./pkg/urls-reader/
COPY urls.txt ./

# compile the application
RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping ./cmd/js-network-api

# run the binary file
CMD ["/docker-gs-ping"]

# CLI to run docker & save the output file
# docker build -f Dockerfile.js-network-api -t js-network-api .
# docker run --rm -v "$(pwd)/output:/app" js-network-api
