# ---- builder stage ----
FROM golang:1.26 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /app/headless-browser ./cmd/headless-browser

# ---- final stage ----
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y chromium ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/headless-browser .
COPY ./urls.txt ./urls.txt

CMD ["./headless-browser"]
